---

- hosts: "localhost"
  gather_facts: no
  connection: local
  remote_user: "{{ user }}"
  vars_files:
  - "vars/main.yml"

  tasks:
  roles:
      - ansible-brew
      - ansible-cask
      - ansible-awscli
