---
# tasks file for cask

  - name: Update Homebrew
    homebrew:
      update_homebrew=yes

  - name: Install Brew Caskroom
    homebrew:
      name=cask
      state=present

  - name: Change the cask directory to /Applications
    lineinfile:
      dest=~/.profile
      insertafter=EOF
      state=present
      line="export HOMEBREW_CASK_OPTS="--appdir=/Applications""

  - name: Add the Casks
    homebrew_cask:
      name={{ item }}
      state=present
    with_items:
      - amazon-music
      - amazon-workspaces
      - anvil
      - appcleaner
      - caffeine
      - chrome-devtools
      - cord
      - dash
      - dayone-cli
      - dogecoin
      - dropbox
      - evernote
      - github-desktop
      - google-chrome
      - google-hangouts
      - gpgtools
      - handbrake
      - intellij-idea
      - iphone-backup-extractor
      - istat-menus
      - istumbler
      - iterm2
      - java
      - macdown
      - mactex
      - macvim
      - mysqlworkbench
      - mamp
      - nmap
      - owasp-zap
      - pgadmin3
      - sublime-text
      - terraform
      - textwrangler
      - tower
      - transmit
      - transmission
      - tunnelblick
      - virtualbox
      - vmware-fusion
      - xquartz
      - wireshark
